#!/bin/bash
#
## Diese Version von "insmod" fügt ein Modul nicht in diesen, sondern in
## den nächsten Kernel ein...

FILE=$1

VERSION=$(getversion)
dir=/lib/modules/$VERSION
touch $dir/../modules.isdn.all
echo $FILE >>$dir/../modules.isdn.all
rm -f $dir/isdn/$FILE
cp $FILE $dir/isdn/$FILE &

exit 0
