:

PATH=/bin:/usr/bin:/etc:/usr/etc

	name=qinfo

#
#	Install the driver object file
#
	rm -f /etc/boot.d/$name
	ln /etc/install.d/boot.d/$name /etc/boot.d/$name

#
#	Install the driver master file
#
	echo 'include .' >/etc/master.d/$name
	echo 'if . include streamlib' >>/etc/master.d/$name
	echo 'x	-	qinfo	-	1	1' >>/etc/master.d/$name
	chown bin /etc/master.d/$name
	chgrp bin /etc/master.d/$name
	chmod 644 /etc/master.d/$name

