
SHELL	= /bin/sh

HEADERS	= alaw.h config.h dump.h isdn3_phone.h isdn_12.h isdn_2.h isdn_23.h \
	isdn_3.h isdn_34.h isdn_limits.h isdn_proto.h kernel.h lap.h msgtype.h \
	phone_1TR6.h primitives.h proto.h q_data.h sioctl.h smallq.h streamlib.h \
	streams.h timeout.h v110.h x75.h x75lib.h

SOURCES =
OBJ	= 
ALL =

all prog lib install update clean depend load:

indent:
	../indent.sh $(HEADERS) $(SOURCES)


