
SHELL	= /bin/sh
MAKE	= make
##  =()<P	= @<P>@>()=
P	= 

##  =()<CC	= @<CC>@>()=
CC	= gcc.new
##  =()<DEFS    = @<DEFCARDS>@ @<KERNEL>@>()=
DEFS    = -I../../include -DKERNEL
##  =()<CFLAGS	= @<CFLAGS>@ @<DEFCARDS>@ @<KERNEL>@>()=
CFLAGS	= -g -O2 -W -Wreturn-type -Wshadow -Wcomment  -I../../include -DKERNEL

##  =()<SYS	= @<SYS>@>()=
SYS	= aux

SOURCES	= leo.c

OBJ	= leo.o
ALL = leo

all:	$(OBJ)	$(ALL)

lib:

indent:
	../../indent.sh $(SOURCES)

depend:		Makefile $(SOURCES)
	makedepend $(DEFS) $(SOURCES)

clean:
	rm -f $(OBJ) $(ALL)

leo:	leo.o # trace.o
		ld -o $@ -x -r $< # /usr/lib/unshared.ld

install update:	install.leo

install.leo:	/etc/init.d/leonardo /etc/boot.d/leonardo /etc/master.d/leonardo

/etc/init.d/leonardo:	leo.init
		super cp leo.init /etc/init.d/leonardo
/etc/master.d/leonardo:	leo.master
		super cp leo.master /etc/master.d/leonardo
/etc/boot.d/leonardo: leo
		super cp leo /etc/boot.d/leonardo

# DO NOT DELETE THIS LINE -- make depend depends on it.

leo.o: /usr/include/sys/types.h /usr/include/sys/time.h
leo.o: /usr/include/sys/signal.h /usr/include/sys/param.h
leo.o: /usr/include/sys/sysmacros.h /usr/include/sys/stream.h
leo.o: /usr/include/sys/stropts.h /usr/include/sys/user.h
leo.o: /usr/include/sys/errno.h /usr/include/sys/reg.h /usr/include/sys/var.h
leo.o: /usr/include/sys/ioctl.h /usr/include/sys/termio.h
leo.o: /usr/include/stddef.h ../../include/streamlib.h
leo.o: ../../include/streams.h /usr/include/sys/uio.h ../../include/config.h
leo.o: ../../include/isdn_12.h ../../include/smallq.h
leo.o: ../../include/primitives.h leo.h
