#!/bin/sh
#
## Diese Version von "insmod" fügt ein Modul nicht in diesen, sondern in
## den nächsten Kernel ein...

FILE=$1

VERSION=${VERSION:-$(${TOPDIR}/tools/getversion)}
dir=${MODDIR}/${VERSION}
echo MOD $(basename d_$FILE .o) >>$TOPDIR/modules.isdn
rm -f $dir/isdn/d_$FILE
(
cp $FILE $dir/isdn/d_$FILE 
strip --strip-debug $dir/isdn/d_$FILE 
) &

exit 0
